// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxpdjfkppgoaygdfmaqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4cGRqZmtwcGdvYXlnZGZtYXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTkxODIsImV4cCI6MjA3MTAzNTE4Mn0.VFkqQ23D8D5BqtQ7MCWB05PUSWOjq-Rj1Y_h7zsKfg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});