// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yygmitrobjxsdjggvewz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Z21pdHJvYmp4c2RqZ2d2ZXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTk0NDIsImV4cCI6MjA2Njc5NTQ0Mn0.ApEl5ysKuQenbI1g6JEJ5LrUB_2fb9mwdDGcRdxMz4E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});